CURSOS_PT = {
    "Engenharia Civil": {
        "Ementa - 2011": {
            "1º Semestre": [
                "Cálculo Diferencial e Integral I – CM201",
                "Eletricidade Aplicada – TE144",
                "Expressão Gráfica I – CD027",
                "Geometria Analítica – CM045",
                "Introdução à Engenharia – TC022",
                "Mecânica Geral I – TC021",
                "Programação de Computadores – CI208"
            ],
            "2º Semestre": [
                "Álgebra Linear – CM005",
                "Cálculo Diferencial e Integral II – CM202",
                "Construção Civil I – TC024",
                "Expressão Gráfica II – CD028",
                "Mecânica Geral II – TC023",
                "Métodos Numéricos – CI202"
            ],
            "3º Semestre": [
                "Cálculo III – CM043",
                "Construção Civil II – TC025",
                "Estatística II – CE003",
                "Mecânica dos Fluidos I – TH019",
                "Mecânica Geral III – TC027",
                "Resistência dos Materiais I – TC026",
                "Topografia I – GA069"
            ],
            "4º Semestre": [
                "Introdução à Engenharia Geotécnica – TC029",
                "Ciências do Ambiente – TH022",
                "Materiais de Construção Civil I – TC030",
                "Mecânica dos Fluidos II – TH021",
                "Resistência dos Materiais II – TC028",
                "Sistemas de Transporte – TT046",
                "Topografia II – GA070"
            ],
            "5º Semestre": [
                "Estruturação Sanitária das Cidades – TH025",
                "Hidráulica – TH020",
                "Infra-Estrutura Viária – TT048",
                "Laboratório de Mecânica dos Solos – TC033",
                "Materiais de Construção Civil II – TC031",
                "Mecânica das Estruturas I – TC032"
            ],
            "6º Semestre": [
                "Atividades Formativas – AAC005",
                "Equipamentos de Construção e Conservação – TT047",
                "Hidráulica e Hidrologia Experimental – TH027",
                "Hidrologia – TH024",
                "Materiais de Construção Civil III – TC034",
                "Mecânica das Estruturas II – TC036",
                "Mecânica dos Solos – TC035"
            ],
            "7º Semestre": [
                "Construção Civil III – TC038",
                "Engenharia de Recursos Hídricos – TH026",
                "Engenharia Social – TH045",
                "Estruturas de Concreto I – TC037",
                "Laboratório de Materiais de Construção – TC039",
                "Obras Geotécnicas – TC066",
                "Planejamento de Transportes – TT049",
                "Saneamento Ambiental I – TH028"
            ],
            "8º Semestre": [
                "Construção Civil IV – TC042",
                "Economia de Engenharia I – TT007",
                "Estágio Supervisionado – TC046",
                "Estágio Supervisionado – TH043",
                "Estágio Supervisionado – TT054",
                "Estruturas de Concreto II – TC040",
                "Geotecnia de Fundações – TC041",
                "Pavimentação – TT051",
                "Saneamento Ambiental II – TH029"
            ],
            "9º Semestre": [
                "Administração de Empresas de Engenharia I – TT008",
                "Estrutura de Edifícios I – TC044",
                "Estruturas Metálicas I – TC043",
                "Gerenciamento de Projetos – TC045",
                "Sistemas Prediais, Hidráulicos e Sanitários – TH030",
                "Trabalho Final de Curso I – TC081",
                "Trabalho Final de Curso I – TH061",
                "Trabalho Final de Curso I – TT071"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC082",
                "Trabalho Final de Curso II – TH062",
                "Trabalho Final de Curso II – TT072"
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        },
        "Ementa - 2023": {
            "1º Semestre": [
                "Expressão Gráfica A – CEG019",
                "Fundamentação de Programação de Computadores – CI182",
                "Pré-Cálculo – CM310",
                "Física I – TC501",
                "Química Aplicada – TC502",
                "Introdução à Engenharia e Inovação – TC591",
                "Introdução à Engenharia e Inovação – TH591",
                "Introdução à Engenharia e Inovação – TT591"
            ],
            "2º Semestre": [
                "Métodos Numéricos – CI202",
                "Introdução à Geometria Analítica e Álgebra Linear – CM303",
                "Cálculo 1 – CM311",
                "Desenho Arquitetônico – TC503",
                "Análise Estrutural I – TC504",
                "Física II – TH512"
            ],
            "3º Semestre": [
                "Introdução à Estatística – CE009",
                "Cálculo 2 – CM312",
                "Topografia I – GA175",
                "Construção Civil I – TC505",
                "Análise Estrutural II – TC506",
                "Sistemas Estruturais – TC507",
                "Mecânica dos Fluídos I – TH501",
                "Sistemas de Transporte – TT501"
            ],
            "4º Semestre": [
                "Cálculo 4 – CM314",
                "Topografia II – GA176",
                "Construção Civil II – TC508",
                "Mecânica dos Sólidos I – TC509",
                "Materiais de Construção Civil I – TC510",
                "Laboratório de Materiais de Construção Civil – TC511",
                "Mecânica dos Fluídos II – TH502",
                "Mecânica dos Fluídos Experimental – TH503"
            ],
            "5º Semestre": [
                "Caracterização Geológica - Geotécnica – TC512",
                "Mecânica dos Sólidos II – TC513",
                "Materiais de Construção Civil II – TC514",
                "Hidráulica – TH504",
                "Ciências do Ambiente – TH508",
                "Planejamento e Operação de Transportes – TT502",
                "Engenharia Civil e Sustentabilidade – TC592",
                "Engenharia Civil e Sustentabilidade – TH592",
                "Engenharia Civil e Sustentabilidade – TT592",
            ],
            "6º Semestre": [
                "Hidráulica dos Solos – TC515",
                "Análise Estrutural III – TC516",
                "Construção Civil III – TC517",
                "Hidrologia – TH505",
                "Hidráulica e Hidrologia Experimental – TH506",
                "Equipamentos de Terraplanagem e de Pavimentação – TT503",
                "Estruturação das Cidades – TH593",
                "Estruturação das Cidades – TT593"
            ],
            "7º Semestre": [
                "Mecânica dos Solos – TC518",
                "Estruturas de Concreto I – TC519",
                "Gestão de Projetos – TC520",
                "Engenharia de Recursos Hídricos – TH507",
                "Saneamento Ambiental I – TH509",
                "Engenharia Econômica – TT504",
                "Engenharia Urbana – TH594",
                "Engenharia Urbana – TT594"
            ],
            "8º Semestre": [
                "Obras Geotécnicas – TC521",
                "Estruturas de Concreto II – TC522",
                "Saneamento Ambiental II – TH510",
                "Estradas – TT505",
                "Pavimentação – TT506",
                "Laboratório de Transportes – TT507",
                "Economia de Engenharia – TT508",
                "Metodologia do Trabalho Científico e Tecnológico – TT509"
            ],
            "9º Semestre": [
                "Estruturas de Aço – TC523",
                "Estruturas de Madeira – TC524",
                "Engenharia de Fundações – TC525",
                "Eletricidade Aplicada – TE144",
                "Engenharia e Sociedade – TH511",
                "Administração de Empresas – TT510",
                "Trabalho Final de Curso I – TC581",
                "Trabalho Final de Curso I – TH581",
                "Trabalho Final de Curso I – TT581",
                "Projeto de Infraestrutura e Obras Especiais – TC595",
                "Projeto de Infraestrutura e Obras Especiais – TH595",
                "Projeto de Infraestrutura e Obras Especiais – TT595"
            ],
            "10º Semestre": [
                "Trabalho Final de Curso II – TC582",
                "Trabalho Final de Curso II – TH582",
                "Trabalho Final de Curso II – TT582",
                "Trabalho Final de Curso II – TC583",
                "Trabalho Final de Curso II – TH583",
                "Trabalho Final de Curso II – TT583",
                "Estágio Supervisionado Obrigatório – TC585",
                "Estágio Supervisionado Obrigatório – TH585",
                "Estágio Supervisionado Obrigatório – TT585",
                "Projetos de Edifícios – TC596",
                "Projetos de Edifícios – TH596",
            ],
            "Optativas (mínimo 6)": [
                "Avaliação de Impactos Ambientais – TT059",
                "Engenharia de Avaliações – TC064",
                "Engenharia de Tráfego – TT056",
                "Engenharia Econômica de Recursos Hídricos – TH035",
                "Estruturas de Concreto III – TC054",
                "Estruturas de Edifícios II – TC056",
                "Estruturas de Madeira – TC057",
                "Estruturas Metálicas II – TC055",
                "Expressão Gráfica III – CD035",
                "Ferrovias – TT066",
                "Geologia de Engenharia – TC049",
                "Geotecnia Ambiental – TC053",
                "Geotecnia Aplicada as Vias de Transporte – TT065",
                "Geotecnia de Taludes e Contenções – TC052",
                "Gerenciamento de Empreendimentos – TC062",
                "Gerenciamento de Recursos Hídricos – TH036",
                "Gerenciamento de Rodovias e Vias Urbanas – TT063",
                "Hidráulica Ambiental – TH033",
                "Hidráulica Fluvial – TH032",
                "Instalações Prediais Especiais – TC065",
                "Introdução a Engenharia de Segurança do Trabalho – TT068",
                "Legislação e Prática Profissional – TC061",
                "Logística e Transporte – TT058",
                "Mecânica das Rochas – TC051",
                "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
                "Modelagem e Planejamento de Transportes Urbanos – TT060",
                "Planejamento e Gestão dos Sistemas Urbanos – TH042",
                "Pontes e Estruturas Especiais – TC058",
                "Portos e Hidrovias – TT067",
                "Projeto de Obras Viárias – TT064",
                "Projetos de Arquitetura – TC060",
                "Projetos de Drenagem Urbana – TH037",
                "Projetos de Obras Hidráulicas – TH031",
                "Projetos de Obras Viárias – TT064",
                "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
                "Projetos de Sistemas de Saneamento Ambiental – TH039",
                "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
                "Qualidade e Conservação Ambiental – TH041",
                "Segurança Viária – TT061",
                "Sistemas de Recursos Hídricos – TH034",
                "Técnica de Investigação Geotécnica e Instrumentação – TC050",
                "Tópicos Avançados de Pavimentação – TT062",
                "Tópicos Avançados em Geotecnia – TC048",
                "Transporte Público – TT057"
            ]
        }
    }
}
