CURSOS_EN = {
    "Civil Engineering": {
        "Syllabus - 2011": {
            "1st Semester": [
                "Differential and Integral Calculus I – CM201",
                "Applied Electricity – TE144",
                "Graphic Expression I – CD027",
                "Analytical Geometry – CM045",
                "Introduction to Engineering – TC022",
                "General Mechanics I – TC021",
                "Computer Programming – CI208"
            ],
            "2nd Semester": [
                "Linear Algebra – CM005",
                "Differential and Integral Calculus II – CM202",
                "Civil Construction I – TC024",
                "Graphic Expression II – CD028",
                "General Mechanics II – TC023",
                "Numerical Methods – CI202"
            ],
            "3rd Semester": [
                "Calculus III – CM043",
                "Civil Construction II – TC025",
                "Statistics II – CE003",
                "Fluid Mechanics I – TH019",
                "General Mechanics III – TC027",
                "Strength of Materials I – TC026",
                "Topography I – GA069"
            ],
            "4th Semester": [
                "Introduction to Geotechnical Engineering – TC029",
                "Environmental Science – TH022",
                "Construction Materials I – TC030",
                "Fluid Mechanics II – TH021",
                "Strength of Materials II – TC028",
                "Transportation Systems – TT046",
                "Topography II – GA070"
            ],
            "5th Semester": [
                "Sanitary Infrastructure of Cities – TH025",
                "Hydraulics – TH020",
                "Roadway Infrastructure – TT048",
                "Soil Mechanics Laboratory – TC033",
                "Construction Materials II – TC031",
                "Structural Mechanics I – TC032"
            ],
            "6th Semester": [
                "Formative Activities – AAC005",
                "Construction and Conservation Equipment – TT047",
                "Experimental Hydraulics and Hydrology – TH027",
                "Hydrology – TH024",
                "Construction Materials III – TC034",
                "Structural Mechanics II – TC036",
                "Soil Mechanics – TC035"
            ],
            "7th Semester": [
                "Civil Construction III – TC038",
                "Water Resources Engineering – TH026",
                "Social Engineering – TH045",
                "Concrete Structures I – TC037",
                "Construction Materials Laboratory – TC039",
                "Geotechnical Works – TC066",
                "Transport Planning – TT049",
                "Environmental Sanitation I – TH028"
            ],
            "8th Semester": [
                "Civil Construction IV – TC042",
                "Engineering Economy I – TT007",
                "Supervised Internship – TC046",
                "Supervised Internship – TH043",
                "Supervised Internship – TT054",
                "Concrete Structures II – TC040",
                "Foundation Geotechnics – TC041",
                "Pavement – TT051",
                "Environmental Sanitation II – TH029"
            ],
            "9th Semester": [
                "Engineering Management I – TT008",
                "Building Structures I – TC044",
                "Steel Structures I – TC043",
                "Project Management – TC045",
                "Building Systems, Hydraulic and Sanitary – TH030",
                "Final Course Project I – TC081",
                "Final Course Project I – TH061",
                "Final Course Project I – TT071"
            ],
            "10th Semester": [
                "Final Course Project II – TC082",
                "Final Course Project II – TH062",
                "Final Course Project II – TT072"
            ],
            "Electives (minimum 6)": [
                "Environmental Impact Assessment – TT059",
                "Engineering Valuations – TC064",
                "Traffic Engineering – TT056",
                "Economic Engineering of Water Resources – TH035",
                "Concrete Structures III – TC054",
                "Building Structures II – TC056",
                "Wood Structures – TC057",
                "Steel Structures II – TC055",
                "Graphic Expression III – CD035",
                "Railways – TT066",
                "Engineering Geology – TC049",
                "Environmental Geotechnics – TC053",
                "Applied Geotechnics to Transport Routes – TT065",
                "Landslide and Retaining Structures Geotechnics – TC052",
                "Project Management – TC062",
                "Water Resources Management – TH036",
                "Highways and Urban Roads Management – TT063",
                "Environmental Hydraulics – TH033",
                "River Hydraulics – TH032",
                "Specialized Building Installations – TC065",
                "Introduction to Occupational Safety Engineering – TT068",
                "Legislation and Professional Practice – TC061",
                "Logistics and Transport – TT058",
                "Rock Mechanics – TC051",
                "Finite Element Method Applied to Structural Engineering – TC059",
                "Urban Transport Planning and Modeling – TT060",
                "Planning and Management of Urban Systems – TH042",
                "Bridges and Special Structures – TC058",
                "Ports and Waterways – TT067",
                "Road Works Project – TT064",
                "Architecture Projects – TC060",
                "Urban Drainage Projects – TH037",
                "Hydraulic Works Projects – TH031",
                "Road Works Projects – TT064",
                "Urban Solid Waste Management Projects – TH038",
                "Environmental Sanitation Projects – TH039",
                "Sanitary Hydraulic Systems Projects – TH040",
                "Environmental Quality and Conservation – TH041",
                "Road Safety – TT061",
                "Water Resources Systems – TH034",
                "Geotechnical Investigation and Instrumentation Techniques – TC050",
                "Advanced Pavement Topics – TT062",
                "Advanced Geotechnics Topics – TC048",
                "Public Transport – TT057"
            ]
        },
        "Syllabus - 2023": {
            "1st Semester": [
                "Graphic Expression A – CEG019",
                "Fundamentals of Computer Programming – CI182",
                "Pre-Calculus – CM310",
                "Physics I – TC501",
                "Applied Chemistry – TC502",
                "Introduction to Engineering and Innovation – TC591",
                "Introduction to Engineering and Innovation – TH591",
                "Introduction to Engineering and Innovation – TT591"
            ],
            "2nd Semester": [
                "Numerical Methods – CI202",
                "Introduction to Analytical Geometry and Linear Algebra – CM303",
                "Calculus 1 – CM311",
                "Architectural Drawing – TC503",
                "Structural Analysis I – TC504",
                "Physics II – TH512"
            ],
            "3rd Semester": [
                "Introduction to Statistics – CE009",
                "Calculus 2 – CM312",
                "Topography I – GA175",
                "Civil Construction I – TC505",
                "Structural Analysis II – TC506",
                "Structural Systems – TC507",
                "Fluid Mechanics I – TH501",
                "Transportation Systems – TT501"
            ],
            "4th Semester": [
                "Calculus 4 – CM314",
                "Topography II – GA176",
                "Civil Construction II – TC508",
                "Solid Mechanics I – TC509",
                "Construction Materials I – TC510",
                "Civil Construction Materials Laboratory – TC511",
                "Fluid Mechanics II – TH502",
                "Experimental Fluid Mechanics – TH503"
            ],
            "5th Semester": [
                "Geological Characterization - Geotechnical – TC512",
                "Solid Mechanics II – TC513",
                "Construction Materials II – TC514",
                "Hydraulics – TH504",
                "Environmental Science – TH508",
                "Transport Planning and Operation – TT502",
                "Civil Engineering and Sustainability – TC592",
                "Civil Engineering and Sustainability – TH592",
                "Civil Engineering and Sustainability – TT592",
            ],
            "6th Semester": [
                "Soil Hydraulics – TC515",
                "Structural Analysis III – TC516",
                "Civil Construction III – TC517",
                "Hydrology – TH505",
                "Experimental Hydraulics and Hydrology – TH506",
                "Earthmoving and Paving Equipment – TT503",
                "City Structuring – TH593",
                "City Structuring – TT593"
            ],
            "7th Semester": [
                "Soils Mechanics – TC518",
                "Concrete Structures I – TC519",
                "Project Management – TC520",
                "Water Resources Engineering – TH507",
                "Environmental Sanitation I – TH509",
                "Engineering Economy – TT504",
                "Urban Engineering – TH594",
                "Urban Engineering – TT594"
            ],
            "8th Semester": [
                "Geotechnical Works – TC521",
                "Concrete Structures II – TC522",
                "Environmental Sanitation II – TH510",
                "Roads – TT505",
                "Pavement – TT506",
                "Transportation Laboratory – TT507",
                "Engineering Economy – TT508",
                "Methodology of Scientific and Technological Work – TT509"
            ],
            "9th Semester": [
                "Steel Structures – TC523",
                "Wood Structures – TC524",
                "Foundation Engineering – TC525",
                "Applied Electricity – TE144",
                "Engineering and Society – TH511",
                "Business Administration – TT510",
                "Final Course Project I – TC581",
                "Final Course Project I – TH581",
                "Final Course Project I – TT581",
                "Infrastructure and Special Works Project – TC595",
                "Infrastructure and Special Works Project – TH595",
                "Infrastructure and Special Works Project – TT595"
            ],
            "10th Semester": [
                "Final Course Project II – TC582",
                "Final Course Project II – TH582",
                "Final Course Project II – TT582",
                "Final Course Project II – TC583",
                "Final Course Project II – TH583",
                "Final Course Project II – TT583",
                "Supervised Internship – TC585",
                "Supervised Internship – TH585",
                "Supervised Internship – TT585",
                "Building Projects – TC596",
                "Building Projects – TH596",
            ],
            "Electives (minimum 6)": [
                "Environmental Impact Assessment – TT059",
                "Engineering Valuations – TC064",
                "Traffic Engineering – TT056",
                "Economic Engineering of Water Resources – TH035",
                "Concrete Structures III – TC054",
                "Building Structures II – TC056",
                "Wood Structures – TC057",
                "Steel Structures II – TC055",
                "Graphic Expression III – CD035",
                "Railways – TT066",
                "Engineering Geology – TC049",
                "Environmental Geotechnics – TC053",
                "Applied Geotechnics to Transport Routes – TT065",
                "Landslide and Retaining Structures Geotechnics – TC052",
                "Project Management – TC062",
                "Water Resources Management – TH036",
                "Highways and Urban Roads Management – TT063",
                "Environmental Hydraulics – TH033",
                "River Hydraulics – TH032",
                "Specialized Building Installations – TC065",
                "Introduction to Occupational Safety Engineering – TT068",
                "Legislation and Professional Practice – TC061",
                "Logistics and Transport – TT058",
                "Rock Mechanics – TC051",
                "Finite Element Method Applied to Structural Engineering – TC059",
                "Urban Transport Planning and Modeling – TT060",
                "Planning and Management of Urban Systems – TH042",
                "Bridges and Special Structures – TC058",
                "Ports and Waterways – TT067",
                "Road Works Project – TT064",
                "Architecture Projects – TC060",
                "Urban Drainage Projects – TH037",
                "Hydraulic Works Projects – TH031",
                "Road Works Projects – TT064",
                "Urban Solid Waste Management Projects – TH038",
                "Environmental Sanitation Projects – TH039",
                "Sanitary Hydraulic Systems Projects – TH040",
                "Environmental Quality and Conservation – TH041",
                "Road Safety – TT061",
                "Water Resources Systems – TH034",
                "Geotechnical Investigation and Instrumentation Techniques – TC050",
                "Advanced Pavement Topics – TT062",
                "Advanced Geotechnics Topics – TC048",
                "Public Transport – TT057"
            ]
        }
    }
}
