dicionario_disciplinas = {
    "1ª Coloracao Disciplina": [
        "",
        "Cálculo Diferencial e Integral I – CM201",
        "Mecânica Geral II – TC023",
        "Materiais de Construção Civil I – TC030",
        "Atividades Formativas – AAC005",
        "Laboratório de Materiais de Construção – TC039",
        "Pavimentação – TT051",
        "Trabalho Final de Curso II – TH062",
        "Ferrovias – TT066",
        "Fundamentos Físicos e Matemáticos para Edificações – EDF1001",
        "Projeto Integrado – EDF1025"
    ],
    "2ª Coloracao Disciplina": [
        "",
        "Eletricidade Aplicada – TE144",
        "Métodos Numéricos – CI202",
        "Mecânica dos Fluidos II – TH021",
        "Equipamentos de Construção e Conservação – TT047",
        "Obras Geotécnicas – TC066",
        "Saneamento Ambiental II – TH029",
        "Trabalho Final de Curso II – TT072",
        "Geologia de Engenharia – TC049",
        "Legislação e Prática Profissional – TC061",
        "Informática Instrumental – EDF1002"
    ],
    "3ª Coloracao Disciplina": [
        "",
        "Expressão Gráfica I – CD027",
        "Cálculo III – CM043",
        "Resistência dos Materiais II – TC028",
        "Hidráulica e Hidrologia Experimental – TH027",
        "Planejamento de Transportes – TT049",
        "Administração de Empresas de Engenharia I – TT008",
        "Avaliação de Impactos Ambientais – TT059",
        "Geotecnia Ambiental – TC053",
        "Logística e Transporte – TT058",
        "Desenho Técnico – EDF1003"
    ],
    "4ª Coloracao Disciplina": [
        "",
        "Geometria Analítica – CM045",
        "Construção Civil II – TC025",
        "Sistemas de Transporte – TT046",
        "Hidrologia – TH024",
        "Saneamento Ambiental I – TH028",
        "Estrutura de Edifícios I – TC044",
        "Engenharia de Avaliações – TC064",
        "Geotecnia Aplicada as Vias de Transporte – TT065",
        "Mecânica das Rochas – TC051",
        "Desenho Digital Básico – EDF1004"
    ],
    "5ª Coloracao Disciplina": [
        "",
        "Introdução à Engenharia – TC022",
        "Estatística II – CE003",
        "Topografia II – GA070",
        "Materiais de Construção Civil III – TC034",
        "Construção Civil IV – TC042",
        "Estruturas Metálicas I – TC043",
        "Engenharia de Tráfego – TT056",
        "Geotecnia de Taludes e Contenções – TC052",
        "Método dos Elementos Finitos Aplicados a Engenharia de Estruturas – TC059",
        "Técnicas Básicas de Construção Civil – EDF1005"
    ],
    "6ª Coloracao Disciplina": [
        "",
        "Mecânica Geral I – TC021",
        "Mecânica dos Fluidos I – TH019",
        "Estruturação Sanitária das Cidades – TH025",
        "Mecânica das Estruturas II – TC036",
        "Economia de Engenharia I – TT007",
        "Gerenciamento de Projetos – TC045",
        "Engenharia Econômica de Recursos Hídricos – TH035",
        "Gerenciamento de Empreendimentos – TC062",
        "Modelagem e Planejamento de Transportes Urbanos – TT060",
        "Materiais de Construção Civil – EDF1006"
    ],
    "7ª Coloracao Disciplina": [
        "",
        "Programação de Computadores – CI208",
        "Mecânica Geral III – TC027",
        "Hidráulica – TH020",
        "Mecânica dos Solos – TC035",
        "Estágio Supervisionado – TC046",
        "Sistemas Prediais, Hidráulicos e Sanitários – TH030",
        "Estruturas de Concreto III – TC054",
        "Gerenciamento de Recursos Hídricos – TH036",
        "Higiene e Segurança do Trabalho – EDF1007"
    ],
    "8ª Coloracao Disciplina": [
        "",
        "Álgebra Linear – CM005",
        "Resistência dos Materiais I – TC026",
        "Infra-Estrutura Viária – TT048",
        "Construção Civil III – TC038",
        "Estágio Supervisionado – TH043",
        "Trabalho Final de Curso I – TC081",
        "Estruturas de Edifícios II – TC056",
        "Gerenciamento de Rodovias e Vias Urbanas – TT063",
        "Desenho Arquitetônico – EDF1008"
    ],
    "9ª Coloracao Disciplina": [
        "",
        "Cálculo Diferencial e Integral II – CM202",
        "Topografia I – GA069",
        "Laboratório de Mecânica dos Solos – TC033",
        "Engenharia de Recursos Hídricos – TH026",
        "Estágio Supervisionado – TT054",
        "Trabalho Final de Curso I – TH061",
        "Estruturas de Madeira – TC057",
        "Hidráulica Ambiental – TH033",
        "Desenho Digital Avançado – EDF1009"
    ],
    "10ª Coloracao Disciplina": [
        "",
        "Construção Civil I – TC024",
        "Introdução à Engenharia Geotécnica – TC029",
        "Materiais de Construção Civil II – TC031",
        "Engenharia Social – TH045",
        "Estruturas de Concreto II – TC040",
        "Trabalho Final de Curso I – TT071",
        "Estruturas Metálicas II – TC055",
        "Hidráulica Fluvial – TH032",
        "Resistência dos Materiais – EDF1010"
    ],
    "11ª Coloracao Disciplina": [
        "",
        "Expressão Gráfica II – CD028",
        "Ciências do Ambiente – TH022",
        "Mecânica das Estruturas I – TC032",
        "Estruturas de Concreto I – TC037",
        "Geotecnia de Fundações – TC041",
        "Trabalho Final de Curso II – TC082",
        "Expressão Gráfica III – CD035",
        "Instalações Prediais Especiais – TC065",
        "Tecnologia do Concreto – EDF1011"
    ],
    "12ª Coloracao Disciplina": [
        "",
        "Introdução a Engenharia de Segurança do Trabalho – TT068",
        "Projetos de Drenagem Urbana – TH037",
        "Tópicos Avançados em Geotecnia – TC048",
        "Introdução à Geometria Analítica e Álgebra Linear – CM303",
        "Mecânica dos Fluídos I – TH501",
        "Mecânica dos Sólidos II – TC513",
        "Hidrologia – TH505",
        "Engenharia Urbana – TH594",
        "Estruturas de Madeira – TC524",
        "Práticas Básicas de Construção Civil – EDF1012"
    ],
    "13ª Coloracao Disciplina": [
        "",
        "Projetos de Obras Hidráulicas – TH031",
        "Transporte Público – TT057",
        "Cálculo 1 – CM311",
        "Sistemas de Transporte – TT501",
        "Materiais de Construção Civil II – TC514",
        "Hidráulica e Hidrologia Experimental – TH506",
        "Engenharia Urbana – TT594",
        "Engenharia de Fundações – TC525",
        "Técnicas Complementares de Construção Civil – EDF1013"
    ],
    "14ª Coloracao Disciplina": [
        "",
        "Projetos de Obras Viárias – TT064",
        "Expressão Gráfica A – CEG019",
        "Desenho Arquitetônico – TC503",
        "Cálculo 4 – CM314",
        "Hidráulica – TH504",
        "Equipamentos de Terraplanagem e de Pavimentação – TT503",
        "Obras Geotécnicas – TC521",
        "Eletricidade Aplicada – TE144",
        "Mecânica dos Solos e Fundações – EDF1014"
    ],
    "15ª Coloracao Disciplina": [
        "",
        "Projetos de Sistemas de Resíduos Sólidos Urbanos – TH038",
        "Fundamentação de Programação de Computadores – CI182",
        "Análise Estrutural I – TC504",
        "Topografia II – GA176",
        "Ciências do Ambiente – TH508",
        "Estruturação das Cidades – TH593",
        "Estruturas de Concreto II – TC522",
        "Engenharia e Sociedade – TH511",
        "Topografia – EDF1015"
    ],
    "16ª Coloracao Disciplina": [
        "",
        "Projetos de Sistemas de Saneamento Ambiental – TH039",
        "Pré-Cálculo – CM310",
        "Física II – TH512",
        "Construção Civil II – TC508",
        "Planejamento e Operação de Transportes – TT502",
        "Estruturação das Cidades – TT593",
        "Saneamento Ambiental II – TH510",
        "Administração de Empresas – TT510",
        "Sistemas Estruturais – EDF1016"
    ],
    "17ª Coloracao Disciplina": [
        "",
        "Projetos de Sistemas Prediais Hidráulicos Sanitários – TH040",
        "Física I – TC501",
        "Introdução à Estatística – CE009",
        "Mecânica dos Sólidos I – TC509",
        "Engenharia Civil e Sustentabilidade – TC592",
        "Mecânica dos Solos – TC518",
        "Estradas – TT505",
        "Trabalho Final de Curso I – TC581",
        "Teoria das Instalações Elétricas Prediais – EDF1017"
    ],
    "18ª Coloracao Disciplina": [
        "",
        "Qualidade e Conservação Ambiental – TH041",
        "Química Aplicada – TC502",
        "Cálculo 2 – CM312",
        "Materiais de Construção Civil I – TC510",
        "Engenharia Civil e Sustentabilidade – TH592",
        "Estruturas de Concreto I – TC519",
        "Pavimentação – TT506",
        "Trabalho Final de Curso I – TH581",
        "Teoria das Instalações Hidráulicas Prediais – EDF1018"
    ],
    "19ª Coloracao Disciplina": [
        "",
        "Segurança Viária – TT061",
        "Introdução à Engenharia e Inovação – TC591",
        "Topografia I – GA175",
        "Laboratório de Materiais de Construção Civil – TC511",
        "Engenharia Civil e Sustentabilidade – TT592",
        "Gestão de Projetos – TC520",
        "Laboratório de Transportes – TT507",
        "Trabalho Final de Curso I – TT581",
        "Projeto Arquitetônico – EDF1019"
    ],
    "20ª Coloracao Disciplina": [
        "",
        "Sistemas de Recursos Hídricos – TH034",
        "Introdução à Engenharia e Inovação – TH591",
        "Construção Civil I – TC505",
        "Mecânica dos Fluídos II – TH502",
        "Hidráulica dos Solos – TC515",
        "Engenharia de Recursos Hídricos – TH507",
        "Economia de Engenharia – TT508",
        "Projeto de Infraestrutura e Obras Especiais – TC595",
        "Práticas Complementares e Instalações Prediais – EDF1020"
    ],
    "21ª Coloracao Disciplina": [
        "",
        "Técnica de Investigação Geotécnica e Instrumentação – TC050",
        "Introdução a Engenharia e Inovação – TT591",
        "Análise Estrutural II – TC506",
        "Mecânica dos Fluídos Experimental – TH503",
        "Análise Estrutural III – TC516",
        "Saneamento Ambiental I – TH509",
        "Metodologia do Trabalho Científico e Tecnológico – TT509",
        "Projeto de Infraestrutura e Obras Especiais – TH595",
        "Impactos Ambientais – EDF1021"
    ],
    "22ª Coloracao Disciplina": [
        "",
        "Tópicos Avançados de Pavimentação – TT062",
        "Métodos Numéricos – CI202",
        "Sistemas Estruturais – TC507",
        "Caracterização Geológica - Geotécnica – TC512",
        "Construção Civil III – TC517",
        "Engenharia Econômica – TT504",
        "Estruturas de Aço – TC523",
        "Projeto de Infraestrutura e Obras Especiais – TT595",
        "Gestão de Obras – EDF1022"
    ],
    "23ª Coloracao Disciplina": [
        "",
        "Trabalho Final de Curso II – TC583",
        "Trabalho Final de Curso II – TH583",
        "Trabalho Final de Curso II – TT583",
        "Estágio Supervisionado Obrigatório – TC585",
        "Estágio Supervisionado Obrigatório – TH585",
        "Estágio Supervisionado Obrigatório – TT585",
        "Projetos de Edifícios – TC596",
        "Projetos de Edifícios – TH596",
        "Orçamento de Obras – EDF1023"
    ],
    "24ª Coloracao Disciplina": [
        "",
        "Planejamento e Gestão dos Sistemas Urbanos – TH042",
        "Pontes e Estruturas Especiais – TC058",
        "Portos e Hidrovias – TT067",
        "Projeto de Obras Viárias – TT064",
        "Projetos de Arquitetura – TC060",
        "Trabalho Final de Curso II – TC582",
        "Trabalho Final de Curso II – TH582",
        "Trabalho Final de Curso II – TT582",
        "Planejamento de Obras – EDF1024"
    ]
}
